fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    activerecord: "https://github.com/purplehazech/puppet-activerecord.git"
    xmpp:
      repo: "https://github.com/hairmare/puppet-xmpp.git"
      ref: "b6a80e5e1138cee8ea0b30591eeef5731913fa85"
    puppet: "https://github.com/purplehazech/puppet-puppet.git"
  symlinks:
    profile: "#{source_dir}/profile"
    role: "#{source_dir}/role"
