rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
before_install:
  - "bundle"
script:
  - "bundle exec rake lint"
  - "bundle exec rake spec"
env:
  - PUPPET_VERSION=3.4.0
  - PUPPET_VERSION=3.3.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.0.2
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: 1.9.3
      env: PUPPET_VERSION=3.0.2
    - rvm: 1.8.7
      env: PUPPET_VERSION=3.0.2
    - env: PUPPET_VERSION=3.4.0

